# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ready2u-rs485-tem-humi
ARDUINO_LIBS := AUnit
include ../../libraries/EpoxyDuino/EpoxyDuino.mk